name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: self-hosted

    # strategy:
    #   matrix:
    #     node-version: [18.x]

    steps:
        run:  cd client
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: [18.x]
          cache: "npm"
      - name: Install client dependencies
        run: |
          cd job-board-react/client
          npm install
      - name: Build client
        run: |
          cd job-board-react/client
          npm run build
      - name: Install server dependencies
        run: |
          cd job-board-react/server
          npm install

