name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    working-directory: ./job-board-react

    steps:
        run:  cd client
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: [18.x]
          cache: "npm"
      - name: Install Dependencies
        run: |
          cd client
          npm install
          npm run build
          
      - name: Install server dependencies
        run: |
          cd server
          npm install
          pm2 restart