name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      CI: false

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install client dependencies
        run: npm i --prefix client
      - name: Build client
        run: npm run build --prefix client
      - name: Install server dependencies
        run: npm i --prefix server
      - name: Restart server
        run: pm2 restart server.js
