name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    # env:
    # CI: false

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json

      - name: "Create env file"
        run: |
          cd server
          echo "${{ secrets.ENV_FILE }}" > .env
        # echo MONGODB_URL=${{ secrets.MONGODB_URL }} > .env

      # echo "${{ secrets.ENV_SECRETS }}" > .env
      # echo "NEW_SECRET=${{ secrets.NEW_SECRET }}" >> .env // USE THIS TO ADD NEW SECRET TO EXISTING .ENV FILE
      - name: Install client dependencies
        run: |
          cd client
          npm install
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Restart pm2
        run: |
          cd server
          pm2 restart server.js

# For the env files ">" means overwrite the current env file with new one, while ">>" means add to existing env
